// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzWIjuhhpHUwgGYUKeNMxhzkYUHozOD5Q',
    appId: '1:783822487684:web:13256dc9a5ad4a9bdb82d1',
    messagingSenderId: '783822487684',
    projectId: 'sole-space-1',
    authDomain: 'sole-space-1.firebaseapp.com',
    storageBucket: 'sole-space-1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP3mRWfNuyGFjvwsnJKe5yIxlXlMVc7zU',
    appId: '1:783822487684:android:b15d2ecb2efba20ddb82d1',
    messagingSenderId: '783822487684',
    projectId: 'sole-space-1',
    storageBucket: 'sole-space-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0wvVQ9utSiuotZWEdR7PXWI7-ZGVgivk',
    appId: '1:783822487684:ios:3332c9901ac10d8ddb82d1',
    messagingSenderId: '783822487684',
    projectId: 'sole-space-1',
    storageBucket: 'sole-space-1.firebasestorage.app',
    androidClientId: '783822487684-3enmsuaj9a4qoos9f35hejm60n4ctk60.apps.googleusercontent.com',
    iosClientId: '783822487684-i8ccebmkasbe9a8ae4jlddl3qck1fikl.apps.googleusercontent.com',
    iosBundleId: 'com.example.soleSpaceUser1',
  );
}
